### ISSUE TITLE
iOS app no more available

### ISSUE THREAD

**Issue by Baptystes** [AlessandroAU/Chorus32-ESP32LapTimer#100]
Hi! I just noticed the iOS app was no longer available.

**Comment by MeatG** [comment]
Hope this gets fixed... :/

**Comment by AlessandroAU** [comment]
Hi guys, unfortunately I have nothing to do with the iOS or Android apps. I'd ask on facebook
https://www.facebook.com/groups/ChorusRFLaptimer/?ref=br_rs

**Comment by swampmonster** [comment]
Is this still an issue? I looked today and the app linked in the readme is available on the app store.

**Comment by s00500** [comment]
No, pls close @swampmonster  ;-)
