### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by Smeat** [AlessandroAU/Chorus32-ESP32LapTimer#108]
We've never specified a license.
We are also required to attribute the original project (if we have any original code left).

Personally I'd prefer a license with copyleft (like the GPL), but would also be fine with the MIT license like the original project.

Whatever we choose, we need permission from all contributors.

Thoughts? @JyeSmith @AlessandroAU @LuisDiazUgena @mike-levenick @swampmonster

**Comment by LuisDiazUgena** [comment]
Hi!

I've no problem to whatever license we use. Feel confortable with something like GPL as well.

**Comment by swampmonster** [comment]
My personal preference would be for MIT/BSD but i have no objections to GPL if that's what the majority wants.

**Comment by AlessandroAU** [comment]
I have no strong feelings either way, one thing though; if there is still MIT Licensed code in the repo is that still compatible with GPL?

**Comment by swampmonster** [comment]
> I have no strong feelings either way, one thing though; if there is still MIT Licensed code in the repo is that still compatible with GPL?

A quick scan of https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses would indicate that it's compatible. The FSF in normal order wants to nitpick and says there is no such thing as an MIT license and points to the expat and x11 licenses as being the licenses called MIT but both of those are compatible as well so we should be in the clear on that point.

**Comment by Smeat** [comment]
Yes MIT/X11 is no problem. This is one of the reasons I prefer the GPL: We can use code from almost any open source project we like :)

**Comment by swampmonster** [comment]
If we go with the GPL we should probably at least talk to @voroshkov and see if he want's any of his code specifically marked as being MIT or if a general mention of where it came from will suffice.

**Comment by Smeat** [comment]
If we still have code from the original project we must include the license header, so at least in Comms.cpp we are violating that.
Even with permission I'd like to keep (or rather add) the MIT text. Wouldn't feel right to omit that :)

**Comment by JyeSmith** [comment]
I have no preference.  What ever keeps it open and free for anyone to use or commercialise.

**Comment by mike-levenick** [comment]
I am good with whatever you all choose. :) no preferences.
