### ISSUE TITLE
The program size (1569757 bytes) is greater than maximum allowed (1310720 bytes)

### ISSUE THREAD

**Issue by Z1gun** [AlessandroAU/Chorus32-ESP32LapTimer#129]
Build in VScode with platformio extension. In Buttons.cpp change:
from
#ifdef USE_NORMAL_BUTTONS
to
#ifndef USE_NORMAL_BUTTONS

Another, got issue  #127

**Comment by Smeat** [comment]
Seems to be the same Issue as #127, so I think we should continue the discussion there.
