### ISSUE TITLE
IOS no Speaking

### ISSUE THREAD

**Issue by andreasr81** [AlessandroAU/Chorus32-ESP32LapTimer#131]
Hi, is this still in Developing?
I Have no Speaking on IOS, iPhone 14 up to date.

Greets Andreas

**Comment by AlessandroAU** [comment]
The text to speech on IOS is responsibility of the upstream app developer (https://github.com/voroshkov/Chorus-RF-Laptimer#ios-app), I'm an not an IOS developer and unfortunately I have no idea why it doesn't work.
