### ISSUE TITLE
File ESPmDNS.h is missing for compile/upload

### ISSUE THREAD

**Issue by mottex** [AlessandroAU/Chorus32-ESP32LapTimer#2]
I try to upload the laptimer code, but arduino ide - gives the following error message:

ESP32LapTimer:7:21: error: ESPmDNS.h: No such file or directory

compilation terminated.

exit status 1
ESPmDNS.h: No such file or directory

Thanks for your help

**Comment by AlessandroAU** [comment]
You will need to install all the libraries required. You should be able to do it through the library manager 
![mdns](https://user-images.githubusercontent.com/22009829/52175172-b5a81480-27eb-11e9-9e53-1486b2c4c2e5.png)

**Comment by mottex** [comment]
![ide](https://user-images.githubusercontent.com/16286504/52176635-b2923180-27b5-11e9-91bd-1f6365f2bdea.PNG)

Unfortunately it is not shown.... any other suggestions?

**Comment by AlessandroAU** [comment]
I would do I fresh install of the esp32 files through board manager to ensure you're not having issues because of old code

**Comment by mottex** [comment]
It seems there is a problem with the ide board manager:
![board manager](https://user-images.githubusercontent.com/16286504/52177943-951a9300-27c8-11e9-8216-184bd48f4fc9.PNG)

**Comment by mottex** [comment]
Thanks for your help! I have internet connection problems, which caused the above message. 

Now, i got the message - comms.h -
![comms missing](https://user-images.githubusercontent.com/16286504/52181163-37e60800-27ef-11e9-902b-4e9fa6ab9f2e.PNG)
 is missing. Do i have to include an other library? (the File comms.h is in the project folder).

**Comment by AlessandroAU** [comment]
You need to make sure that all the files are in the same folder and that the folder is called "ESP32LapTimer" ie same as the main arduino .ino file.

**Comment by mottex** [comment]
Thanx allessandro! Can be closef
