### ISSUE TITLE
Json package with data

### ISSUE THREAD

**Issue by LuisDiazUgena** [AlessandroAU/Chorus32-ESP32LapTimer#29]
I was thinking about a json rest api to communicate to and from apps.

Could be really easy to create and android app that allows to configurate the project instead of using a webserver.

The app also could be used to visualise lap times.

I have already started digging into how to create the json parser in the esp32, and got plenty of experience in software developing.

Will be nice if you can point out what needs to be changed with the app. I'm thinking about:

Timer active
Frecuency of video
Vbat scale

**Comment by AlessandroAU** [comment]
If you want to develop this you are welcome too, but why would this be better than a websever? You'll need to make the user download another app.

**Comment by LuisDiazUgena** [comment]
Yeah, I was thinking about making it easier, but indeed will be more hard to develope, and a web server is already cross platform.
