### ISSUE TITLE
Channel change

### ISSUE THREAD

**Issue by LuisDiazUgena** [AlessandroAU/Chorus32-ESP32LapTimer#30]
Hi!

How do you modify channels assigned to each ADC?

**Comment by JyeSmith** [comment]
You can do that here https://github.com/AlessandroAU/Chorus32-ESP32LapTimer/blob/master/ESP32LapTimer/HardwareConfig.h

**Comment by LuisDiazUgena** [comment]
Sorry, I mean VRX channels

**Comment by JyeSmith** [comment]
https://github.com/AlessandroAU/Chorus32-ESP32LapTimer/blob/master/ESP32LapTimer/RX5808.ino#L105

**Comment by LuisDiazUgena** [comment]
Thanks!
