### ISSUE TITLE
Connection with LiveTime via WiFi..

### ISSUE THREAD

**Issue by kmitchel** [AlessandroAU/Chorus32-ESP32LapTimer#59]
Use with LiveTime requires serial correct?

**Comment by AlessandroAU** [comment]
There is a bug with the ESP causing TCP disconnects that still hasn't been fixed
https://github.com/espressif/arduino-esp32/issues/1921

So Native TCP connection in livetime doesn't work. 

You can use a UDP -> serial port emulator application to use it over WiFi with livetime. 

https://www.netburner.com/download/virtual-comm-port-driver-windows-xp-10/?fbclid=IwAR2W9V_YzjuP5_u9U-nJx1x38beFWNR0eRI59QOyYO_-NSePmTnW14kk7yA

**Comment by kmitchel** [comment]
Working.  Excellent!! TY.
