### ISSUE TITLE
OTA Programming

### ISSUE THREAD

**Issue by JyeSmith** [AlessandroAU/Chorus32-ESP32LapTimer#93]
Makes sense we should have this and will be useful those of us that bury our boards in a case.

Pulls could also be accompanied with a .bin for easy uploading and testing.

**Comment by AlessandroAU** [comment]
Doesn't the web interface already do this?

**Comment by JyeSmith** [comment]
So it is... 

Ive just never used it during dev, but will be useful in field testing.
